export const JWT_SECRET = process.env.JWT_SECRET;
export const JWT_ACCESS_TOKEN_EXPIRATION_TIME = process.env.JWT_EXPIRATION_TIME;
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME = process.env.JWT_EXPIRATION_TIME;
